[package]
name = "tinyset"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Sylvan Franklin"]
license = "MIT-0"
description = "Simple, consistent, and appealing math homework template"
repository = "https://github.com/sylvanfranklin/tinyset"
categories = ["Layout"]
keywords = ["Math", "HW", "pset", "Minimal"]
exclude = ["*.pdf"]
disciplines = ["mathematics"]
